FROM tobix/pywine

MAINTAINER Gajo Petrovic, gajopetrovic@gmail.com

RUN wine /home/user/.wine/drive_c/Python35-32/python.exe /home/user/.wine/drive_c/Python35-32/Scripts/pip.exe install pyinstaller pyqt5
